### Login
POST http://localhost:3000/auth/signin HTTP/1.1
content-type: application/json

{
    "username": "eduardo@teste.com",
    "password": "Teste@123"
}

### Me
POST http://localhost:3000/auth/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJFZHVhcmRvIiwicGVyZmlsIjoiY2xpZW50ZSIsImlhdCI6MTY5OTkxMDYyMiwiZXhwIjoxNjk5OTk3MDIyfQ._Ga3l4dVCdpdWD5V5OEw2vyf5cduVJpkX8Xwy_0pA0s