### Login
POST http://localhost:3000/auth/signin HTTP/1.1
content-type: application/json

{
    "username": "eduardo@teste.com",
    "password": "Teste@123"
}

### Me
POST http://localhost:3000/auth/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlRlc3RlIiwicGVyZmlsIjoiYWRtaW4iLCJpYXQiOjE2OTk5NjUwODcsImV4cCI6MTcwMDA1MTQ4N30.kg0pGKUv8jNAkJ_rY2HmL5lsJfXnduL4SGNU9XkuZQo