### Login
POST http://localhost:3000/auth/signin HTTP/1.1
content-type: application/json

{
    "username": "eduardo@teste.com",
    "password": "Teste@123"
}

### Me
POST http://localhost:3000/auth/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsIm5hbWUiOiJUZXN0ZSIsInBlcmZpbCI6ImFkbWluIiwiaWF0IjoxNjk5ODM0NzEwLCJleHAiOjE2OTk5MjExMTB9.8KxbnDAn0DPLXcIFHlXTUcR-Vy0tfxyaR2DjWBT8_4I