### FindAll
GET http://localhost:3000/espacos-esportivos HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsIm5hbWUiOiJUZXN0ZSIsInBlcmZpbCI6ImFkbWluIiwiaWF0IjoxNjk5OTA5NTk0LCJleHAiOjE2OTk5OTU5OTR9.5aRZtFHgXZds7znR036Qltuq7jn-W6au4c9W0t6fi-o

### FindOne
GET http://localhost:3000/espacos-esportivos/1 HTTP/1.1

### Create
POST http://localhost:3000/espacos-esportivos HTTP/1.1
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsIm5hbWUiOiJUZXN0ZSIsInBlcmZpbCI6ImFkbWluIiwiaWF0IjoxNjk5OTA5NTk0LCJleHAiOjE2OTk5OTU5OTR9.5aRZtFHgXZds7znR036Qltuq7jn-W6au4c9W0t6fi-o

{
    "tamanho": "1239",
    "capacidade": 1234,
    "tipo_espaco": "quadra",
    "valor_hora": 100,
    "empresa_id": 1
}

### Update
PATCH http://localhost:3000/espacos-esportivos/id HTTP/1.1
Content-Type: application/json

{
    "tamanho": "12asdf39",
    "capacidade": 1212334,
    "tipo_espaco": "qua124dra",
    "valor_hora": 100,
    "empresa_id": 1
}

### Remove
DELETE http://localhost:3000/espacos-esportivos/id HTTP/1.1